name: Flutter Project Build
on:
  push:
    branches:
      - build
jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Default Flutter Action
        uses: ./.github/actions/flutter
      - run: flutter build windows --release
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Default Flutter Action
        uses: ./.github/actions/flutter
      - run: flutter build apk --release
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Default Flutter Action
        uses: ./.github/actions/flutter
      - run: flutter build linux --release
  build-ios:
    runs-on: ubuntu-latest
    steps:
      - name: Default Flutter Action
        uses: ./.github/actions/flutter
      # - run: find . -name "Podfile" -execdir pod install \;
      - run: flutter build ipa --release
  build-macos:
    runs-on: ubuntu-latest
    steps:
      - name: Default Flutter Action
<<<<<<< HEAD
        uses: ./.github/actions/flutter
      - run: flutter build macos --release
=======
        uses: ./.github/actions/flutter/default
      - run: flutter build macos --release
>>>>>>> 0d74378855a282555f48ff26c467ca11091a630c
